# Generated by Django 2.2 on 2023-04-16 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('item_carbs', models.CharField(max_length=200)),
                ('item_fat', models.CharField(max_length=200)),
                ('item_protein', models.CharField(max_length=200)),
                ('item_calories', models.CharField(max_length=200)),
                ('item_notes', models.CharField(max_length=800)),
                ('item_price', models.IntegerField()),
                ('item_image', models.CharField(default='https://liftlearning.com/wp-content/uploads/2020/09/default-image.png', max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocery_list.Item')),
                ('list_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocery_list.List')),
            ],
        ),
    ]
