# Generated by Django 2.2 on 2023-04-23 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='items',
            field=models.ManyToManyField(through='grocery_list.ListItem', to='grocery_list.Item'),
        ),
    ]
