# Generated by Django 2.2 on 2023-04-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0003_auto_20230423_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_notes',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
